
#Ambience Mod Configurations
[Ambience]
	#Defines the sound volume fade in/out duration [Default:25,Range:1~500]
	#Range: 1 ~ 500
	Fade_Duration = 25
	#Show a cinematic enty with a image on enter a structure[Default:true]
	Structures_Cinematic = true
	#Defines the distance in blocks between the player and hostile mobs to determine if still in combat or not [Default:16,Range:10~128]
	#Range: 10 ~ 128
	In_Battle_Distance = 16
	#Fade Out Sound Volume on Game Lost Focus[Default:true]
	Lost_Focus_FadeOut = true

	#Ocarina Configurations
	[Ambience.Ocarina]
		#Enables or disables the Minuet of Forest Song [Default:true]
		Minuet_of_Forest_Song = true
		#Enables or disables the Prelude of Light Song [Default:true]
		Prelude_of_light_Song = true
		#Enables or disables the Horse's Song [Default:true]
		Horse_Song = true
		#Enables or disables the Song of Storms [Default:true]
		Song_of_Storms = true
		#Enables or disables the Sun's Song [Default:true]
		Sun_Song = true
		#Enables or disables the Serenade of Water Song [Default:true]
		Serenade_of_Water_Song = true
		#Enables or disables the Bolero of Fire Song [Default:true]
		Fire_Song = true

